### PR TITLE
Activity checking

### PR DESCRIPTION
**Pull request by ferdianjovan**
Activity checking during out of office hours.
It can be run stand-alone by calling the launch file.
You just need to provide soma config name to get region information, and config file (in yaml) telling when the activity checking should be carried out (Monday to Sunday).

### CODE REVIEW

**Comment by ferdianjovan** [comment]
It will store an entry every time it finishes the checking as a report to mongodb using `robblog/RobblogEntry` definition.
Use people_counter.py if you want to use this somewhere else.
It is based on duration how long the checking should be carried out.

**Comment by ferdianjovan** [comment]
An example of how to use people_counter.py can be seen in https://github.com/strands-project/trajectory_behaviours/pull/20/files#diff-94ec4c61137ce3b58c08469eae19802aR156

config file is a list of lists running from Monday to Sunday (7 lists) with specific time interval defined on each list.

**Comment by hawesie** [comment]
I've merged this, but now I realise I don't understand what to do with this code. Is this already running via Bruno's exploration code?

**Comment by ferdianjovan** [comment]
It is not part of bruno's code. You said you might put my code on your code.
If it will be part of something, it should be part of object/people search if I am not wrong.

**Pull request merged**
