### PR TITLE
Update for Activity Report

### PR DESCRIPTION
**Pull request by ferdianjovan**
New template report with better information inside.
Reduce (just a bit), CPU consumption during both active and inactive sessions from (10% to 8%).

### CODE REVIEW

**Comment by hawesie** [comment]
@kunzel I can merge and test, but I don't know which machine this is running on. Please let me know!

**Comment by kunzel** [comment]
Ferdian's reporting is done within the activity checking action, so I assume bettyl? @ferdianjovan is that right?
The other two reports (temperature and objects) should be triggered by cron (see strands' crontab on bettyr)

**Comment by ferdianjovan** [comment]
Yes, it is running on bettyl now.

**Comment by heuristicus** [comment]
@hawesie suggest we merge this - it's required on the executive machine.

**Pull request merged**
